spring:
  config:
    import: configserver:http://localhost:8888
  application:
    name: sample-service
  profiles:
    active: prod
#  cloud:
#    config:
#      uri: http://localhost:8888
#      enabled: false

#custom:
#  secret: tajne
#  nonsecret: nietajne