spring:
  config:
    import: configserver:http://localhost:8888
  application:
    name: sample-service
  profiles:
    active: dev
#  cloud:
#    config:
#      headers:
#        X-Config-Token: "myroot"
#  cloud:
#    config:
#      uri: http://localhost:8888
#      enabled: false



custom:
  secret: tajne local
  nonsecret: nietajne local