version: "3.8"

services:
  vault:
    image: hashicorp/vault:1.14.0
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "myroot"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    command: >
      server -dev
      -dev-root-token-id=myroot
      -dev-listen-address=0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    networks:
      - vault-net

networks:
  vault-net:
    driver: bridge