server:
  port: 8888

######## Mixed native and vault  ########
spring:
  application:
    name: config-server
  profiles:
    active: composite
  cloud:
    vault:
      host: localhost
      port: 8200
      scheme: http
      authentication: APPROLE
      app-role:
        role-id: ${VAULT_APPROLE_ROLE_ID:8ba259ae-f835-e535-2839-c202e16b44ea}
        secret-id: ${VAULT_APPROLE_SECRET_ID:0e336373-4072-5aed-0f4c-3a11cb1702d1}
    config:
      server:
        failOnCompositeError: true # true - all config have to be success
        composite:
          - type: native
            order: 1
            search-locations:
              - classpath:/config/{application}
          - type: vault
            order: 2
            host: localhost
            port: 8200
            scheme: http
            backend: secret
            profileSeparator: '-' # default ,
            kvVersion: 2
            authentication: APPROLE
            app-role:
              role-id: ${VAULT_APPROLE_ROLE_ID:8ba259ae-f835-e535-2839-c202e16b44ea}
              secret-id: ${VAULT_APPROLE_SECRET_ID:0e336373-4072-5aed-0f4c-3a11cb1702d1}


######## Only native ########

#spring:
#  application:
#    name: config-server
#  profiles:
#    active: native

######## Only vault ########

#spring:
#  application:
#    name: config-server
#  profiles:
#    active: vault
#  cloud:
#    vault:
#      host: localhost
#      port: 8200
#      scheme: http
#      authentication: TOKEN
#      token: myroot
#    config:
#      server:
#        vault:
#          host: localhost
#          port: 8200
#          scheme: http
#          backend: secret
#          kvVersion: 2
#          authentication: TOKEN
#          token: myroot